version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    command: npm run dev

  frontend:
    build:
      context: ./client
    env_file:
      - ./client/.env.docker
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm run dev
    depends_on:
      - server
